### ISSUE TITLE
BRAT complains about xfdumanifest.xml file in Sentinel-3 data

### ISSUE THREAD

**Issue by bmlucas** [BRAT-DEV/main#1]
In Sentinel-3 data package there is always a xfdumanifest.xml, BRAT is complaning about this file in the import dialog if one just adds the Sentinel-3 data package (Sentinel-3 data is always distributed in the data package: one directory with manifest file + one or more measurements files in netcdf format).

The toolbox should ignore the file and not import it, the user has to remove it manually or the processing will not work.

"Task 'CreateOperations_1': BRAT ERROR: exception #-7: CProductList::CheckFiles - Unknown file format - File name: 'C:\Users\lucasB\Documents\EUMETSAT\IPF\L2\20151002_User_TDS_Altimetry_from_CLS\Ocean\S3A_SR_2_WAT____20130131T122437_20130131T122849_20150916T192631_0251_125_237______MAR_O_NT____.SEN3\xfdumanifest.xml' 

===> Task 'CreateOperations_1' (pid 16716) UNSUCCESSFULLY ENDED (code -1) - See messages above <==="

![xfdumanifest xml](https://cloud.githubusercontent.com/assets/15247849/10665115/1b61f8de-78c9-11e5-89c1-fe8ddfd20031.png)

**Comment by bratbox** [comment]
The current approach of the BRAT is to allow to add any type of file when adding data to the Dataset. If the Add Dir option is used all the files within the directory will be added and then the user needs to remove the unwanted files manually. For the next release of the tool, we plan to change this behaviour so that the tool will be more selective on the types of files to be imported and especially the case mentioned will be resolved since XML files will not be processed. This is considered as an improvement for the next major release of the tool.

**Comment by bratbox** [comment]
The new release of the toolbox has implemented this functionality. Now when a folder is imported the toolbox will raise a warning that some files are not loaded, but it loads the netCDF file and ignores the xml files.
